# Reference: https://github.com/CleverRaven/Cataclysm-DDA/blob/master/.github/workflows/matrix.yml
name: Cataclysm Compiler

on:
  workflow_dispatch:
    inputs:
      target-repo:
        description: 'Target repository for compilation'
        required: true
        default: 'CleverRaven'
        type: choice
        options:
          - 'casswedson'
          - 'CleverRaven'
          - 'NOPE'

env:
  target-repo: CleverRaven

concurrency:
  group: cataclysm-build
  cancel-in-progress: true

jobs:
  linux-compiler:
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:

      - name: Clone CDDA
        uses: actions/checkout@v4
        with:
          repository: ${{ env.target-repo || inputs.target-repo }}/Cataclysm-DDA
          fetch-depth: 1
          ref: master

      - name: Install Dependencies
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: libsdl2-dev libsdl2-ttf-dev libsdl2-image-dev libsdl2-mixer-dev clang ccache

      # - name: Install Qt
      #   uses: jurplel/install-qt-action@v3
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
      - name: Build
        run: |
          make -j 10 CCACHE=1 RELEASE=1 TILES=1 SOUND=1 ASTYLE=0 LINTJSON=0 LOCALIZE=0 TESTS=0
          # make object_creator -j 10 RELEASE=1 CCACHE=1 CXXFLAGS="-static -static-libgcc -static-libstdc++"
          # ccache -C
      - name: Package & post
        run: |
          zip cataclysm-tiles.zip cataclysm-tiles
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cataclysm-tiles
          path: ./cataclysm-tiles.zip
          # path: ./object-creator.zip
